# Generated by Django 3.2 on 2022-04-22 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='delete',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
